apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-test
  labels:
    app: nodeapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-test
  template:
    metadata:
      labels:
        app: nodeapp-test
    spec:
      containers:
        - name: nodeapp-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"          # <-- same image you were using before
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}              # <-- adjust to whatever your app listens on
              protocol: TCP

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: node-app
#   labels:
#     app: node-app
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: node-app
#   template:
#     metadata:
#       labels:
#         app: node-app
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: {{ .Values.service.port }}
#               protocol: TCP
      #     volumeMounts:
      #       - name: app-code
      #         mountPath: /usr/src/app
      # volumes:
      #   - name: app-code
      #     hostPath:
      #       path: /run/desktop/mnt/host/c/Users/dsirc/Desktop/Moutusi/Training/Repo/my-argocd-demo # Replace with full path

